# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000


volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  - name: nginx-tmp
    emptyDir: {}

volumeMounts:
  - name: nginx-cache
    mountPath: /var/cache/nginx
    readOnly: false
  - name: run
    mountPath: /var/run
    readOnly: false
  - name: nginx-tmp
    mountPath: /var/lib/nginx/tmp
    readOnly: false
