name: debug-output
description: Print out basic debug info for a k8s cluster

runs:
  using: composite
  steps:
    - name: Print basic debug info for a k8s cluster
      run: |
        echo "::group::kubectl get all"
        uds zarf tools kubectl get all -A || echo "failed" | tee /tmp/debug-k-get-all.log
        echo "::endgroup::"
        echo "::group::kubectl get pv,pvc"
        uds zarf tools kubectl get pv,pvc -A || echo "failed" | tee /tmp/debug-k-get-pv-pvc.log
        echo "::endgroup::"
        echo "::group::kubectl get package"
        uds zarf tools kubectl get package -A || echo "failed" | tee /tmp/debug-k-get-package.log
        echo "::endgroup::"
        echo "::group::kubectl get events"
        uds zarf tools kubectl get events -A --sort-by='.lastTimestamp' || echo "failed" | tee /tmp/debug-k-get-events.log
        echo "::endgroup::"
        echo "::group::kubectl describe nodes"
        uds zarf tools kubectl describe nodes k3d-uds-server-0 || echo "failed" | tee /tmp/debug-k-describe-node.log
        echo "::endgroup::"
      shell: bash
