include:
  # include the component located in the current project from the current SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/commitlint@$CI_COMMIT_SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/lint@$CI_COMMIT_SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/test@$CI_COMMIT_SHA
    inputs:
      flavor: $FLAVOR
      type: $TYPE
  # - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/publish@$CI_COMMIT_SHA

# publish:
#   needs: [test]
#   parallel:
#     matrix:
#       - FLAVOR: [unicorn]
#         TYPE: [install]
#         ARCH: [amd64]

test:
  parallel:
    matrix:
      - FLAVOR: [upstream, registry1] # TODO need secrets to add other flavors
        TYPE: [install] # TODO need upgrade check stuff to enable upgrade type

job_with_id_tokens:
  id_tokens:
    FIRST_ID_TOKEN:
      aud: https://first.service.com
    SECOND_ID_TOKEN:
      aud: https://second.service.com
  script:
    - echo first-service-authentication-script.sh $FIRST_ID_TOKEN
    - echo second-service-authentication-script.sh $SECOND_ID_TOKEN
