# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/commitlint@$CI_COMMIT_SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/lint@$CI_COMMIT_SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/test@$CI_COMMIT_SHA
    inputs:
      # if you have additional report artifacts to add to the gitlab
      # artifact zip file you can add the path here and the entire directory
      # will be included
      # reports-path: sample-reports/playwright
      flavor: $FLAVOR
      type: $TYPE
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/publish@$CI_COMMIT_SHA
    inputs:
      flavor: $FLAVOR
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/scorecard@$CI_COMMIT_SHA

test:
  artifacts:
    # if you have specific report types that are natively supported by
    # gitlab you can include those here and they'll be included in addition to the
    # artifact containing debug logs, oscal, etc.
    # (e.g. Junit tests, sast reports, etc)
    # see: https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html
    # reports:
    #   junit: sample-reports/junit.xml
  parallel:
    matrix:
      - FLAVOR: [upstream]
        TYPE: [install]
      # - FLAVOR: [upstream, registry1, unicorn]
      #   TYPE: [install]
      # - FLAVOR: [upstream, registry1]
      #   TYPE: [upgrade]

publish:
  parallel:
    matrix:
      - FLAVOR: [upstream]
