apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: podinfo
  namespace: podinfo
spec:
  network:
    expose:
      - service: podinfo
        podLabels:
          app: podinfo
        host: podinfo
        gateway: tenant
        port: 9898
