# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/main/tasks.schema.json

variables:
  - name: CHART_PATH
    description: Relative path to the directory with the uds-config chart
    default: chart/
  - name: GROUP_NAME
    description: The name of the niche/group that the package fits into. (e.g. package,swf,lfai)
    default: package
  - name: COMMON_ZARF
    description: Whether or not there is a common zarf.yaml file
    default: "true"
  - name: PACKAGE_DIR
    description: Base directory where packages are located, relative to the root of the repository
    default: .

tasks:
  - name: verify-badge
    description: Verifies that a UDS Package implements UDS Package Practices flagging things that are out of compliance
    actions:
      - description: "Deprecated: Verify Badge"
        cmd: echo "Skipping badge verification. This task's functionality will be removed or replaced in a future release."
