tasks:
  - name: commit
    description: Commit file changes back to the repository
    inputs:
      git-user-name:
        description: The username for Git config
        default: "UDS Commit Bot"
      git-email-address:
        description: The email used for Git config
        default: "uds-commit-bot@defenseunicorns.com"
      git-gpg-key:
        description: Path to the GPG key used to sign git commits
    actions:
      - description: Git configuration setup
        cmd: |
          set -e pipefail
          git config --global user.name ${{ .inputs.git-user-name }}
          git config --global user.email ${{ .inputs.git-email-address }}
          if [ -n ${{ .inputs.git-gpg-key }} ]; then
            git config --global user.signingkey ${{ .inputs.git-gpg-key }}
            echo ${{ .inputs.git-gpg-key }} | gpg --import
            echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          fi
      - description: Commit and push updated files
        inputs:
          changed-files:
            description: Path to the file(s) changed
            default: /oscal.yaml
          git-gpg-key:
            description: Path to the GPG key used to sign git commits
        cmd: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git add ${{ .inputs.changed-files }}
          if [ -n ${{ .inputs.gpgkey }} ]; then
            git commit -S -m "UDS Commit Bot updated file(s)"
            git push origin "HEAD:$CURRENT_BRANCH"
          else
            git push origin "HEAD:$CURRENT_BRANCH"
          fi
