variables:
  - name: PKG_PATH
    description: Path to the zarf package to scan
  - name: OUTPUT_FORMAT
    description: Scan output format
    default: json
  - name: VERSION
    description: Version of uds-security-hub to use
    default: latest

tasks:
  - name: scan
    actions:
      - description: scan the provided PKG_PATH
        cmd: |
          CVE_SCAN=cve-scan.${OUTPUT_FORMAT}

          FILE_TO_SCAN=$(realpath ${PKG_PATH})

          docker run --rm \
              --pull always \
              -v $FILE_TO_SCAN:$FILE_TO_SCAN \
            ghcr.io/defenseunicorns/uds-security-hub:${VERSION} \
              --package-path $FILE_TO_SCAN \
              --output-format ${OUTPUT_FORMAT} \
              > "${CVE_SCAN}"

          echo $CVE_SCAN
        setVariables:
          - name: CVE_SCAN
