variables:
  - name: PKG_PATH
    description: Path to the zarf package to scan
  - name: OUTPUT_FORMAT
    description: Scan output format
    default: json
  - name: VERSION
    description: Version of uds-security-hub to use
    default: latest
  - name: COSIGN_VERSION
    description: sion of cosign to use
    default: v2.4.0

tasks:
  - name: scan
    actions:
      - description: run scan against the path
        cmd: |
          CVE_SCAN=cve-scan.${OUTPUT_FORMAT}

          FILE_TO_SCAN=$(realpath ${PKG_PATH})

          docker run --rm \
              --pull always \
              -v $FILE_TO_SCAN:$FILE_TO_SCAN \
            ghcr.io/defenseunicorns/uds-security-hub:${VERSION} \
              --package-path $FILE_TO_SCAN \
              --output-format ${OUTPUT_FORMAT} \
              > "${CVE_SCAN}"

          echo $CVE_SCAN
        setVariables:
          - name: CVE_SCAN
      - description: create the cosign bundle
        cmd: |
          COSIGN_BUNDLE="cosign.bundle"
          env
          docker run -e GITHUB_TOKEN -v $PWD:$PWD -w $PWD --rm gcr.io/projectsigstore/cosign:${COSIGN_VERSION} sign-blob --bundle $COSIGN_BUNDLE --yes ${CVE_SCAN}
          echo $COSIGN_BUNDLE
        setVariables:
          - name: COSIGN_BUNDLE
