name: security-hub-scan
description: Scans a zarf package with uds-security-hub

inputs:
  path:
    description: Path to the zarf package to scan
    required: true
  format:
    description: Scan output format
    default: json
  version:
    description: Version of uds-security-hub to use
    default: v0.0.11

outputs:
  results:
    description: a file that contains the results in the desired format
    value: ${{ steps.scan.outputs.results }}
  format:
    description: the format used to generate the results, useful in subsequent steps (i.e. archive)
    value: ${{ inputs.format }}
  cosign:
    description: a cosign bundle for verifying the authenticity of the scan results
    value: ${{ steps.cosign.outputs.cosign }}

runs:
  using: composite
  steps:
    - name: install cosign
      uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0

    - name: use uds-security-hub to scan a package
      id: scan
      run: |
        OUTPUT_FILE=$(mktemp --suffix .${{ inputs.format }})
        docker run --rm \
            -v $PWD:/wrk -w /wrk \
          ghcr.io/defenseunicorns/uds-security-hub:${{ inputs.version }} \
            --package-path ${{ inputs.path }} \
            --output-format ${{ inputs.format }} \
            > "${OUTPUT_FILE}"

        echo "created results in ${OUTPUT_FILE}"

        echo "results=${OUTPUT_FILE}" >> "$GITHUB_OUTPUT"
        echo "format=${{ inputs.format }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: sign results
      id: cosign
      env:
          COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign-blob --bundle cosign.bundle --yes ${{ steps.scan.outputs.results }}
        echo "cosign=cosign.bundle" >> $GITHUB_OUTPUT
      shell: bash