name: security-hub-scan
description: Scans a zarf package with uds-security-hub

inputs:
  path:
    description: Path to the zarf package to scan
    required: true
  format:
    description: Scan output format
    default: json
  version:
    description: Version of uds-security-hub to use
    default: v0.0.11

runs:
  using: composite
  steps:
    - name: use uds-security-hub to scan a package
      run: |
        OUTPUT_FILE=$(mktemp --suffix .${{ inputs.format }})
        docker run --rm -v $PWD:/wrk -w /wrk ghcr.io/defenseunicorns/uds-security-hub:${{ inputs.version }} \
          --package-path ${{ inputs.path }} \
          --output-format ${{ inputs.format }} \
          --output-file "${OUTPUT_FILE}"

        echo "created results in ${OUTPUT_FILE}"

        echo "output=${OUTPUT_FILE}" > "$GITHUB_OUTPUT"
      shell: bash
