name: security-hub-scan
description: Scans a zarf package with uds-security-hub

inputs:
  path:
    description: Path to the zarf package to scan
    required: true
  format:
    description: Scan output format
    default: json
  version:
    description: Version of uds-security-hub to use
    default: v0.0.11

outputs:
  results:
    description: a directory that contains the results in the desired format and a cosign bundle
    value: ${{ steps.tmpdir.outputs.dir }}

runs:
  using: composite
  steps:
    - name: install cosign
      uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
    
    - name: create tmpdir for output
      id: tmpdir
      run: |
        tmpdir=$(mktemp -d)
        echo "dir=$tmpdir" >> $GITHUB_OUTPUT
      shell: bash

    - name: use uds-security-hub to scan a package
      id: scan
      run: |
        OUTPUT_FILE=${{ steps.tmpdir.outputs.dir }}/results.${{ inputs.format }}

        docker run --rm \
            -v $PWD:/wrk -w /wrk \
          ghcr.io/defenseunicorns/uds-security-hub:${{ inputs.version }} \
            --package-path ${{ inputs.path }} \
            --output-format ${{ inputs.format }} \
            > "${OUTPUT_FILE}"

        echo "created results in ${OUTPUT_FILE}"
      shell: bash

    - name: sign results
      id: cosign
      env:
          COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign-blob --bundle ${{ steps.tmpdir.outputs.dir }}/cosign.bundle --yes ${{ steps.scan.outputs.results }}
      shell: bash