name: save-logs
description: Save debug logs

inputs:
  suffix:
    description: Suffix to append to the debug log
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/zarf-*.log || echo ""
        sudo chown $USER /tmp/uds-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: debug-log${{ inputs.suffix }}
        path: |
          /tmp/zarf-*.log
          /tmp/uds-*.log
