name: Test-Deploy
description: Test the UDS package

inputs:
  flavor:
    description: Flavor of the package to test
    required: true
  type:
    description: Whether to run upgrade tests
    default: install
  options:
    description: Additional CLI options for test workflows
    default: ""

runs:
  using: composite
  steps:
    # === INSTALL TESTING ===

    - name: Test installing the package
      if: ${{ inputs.type == 'install' }}
      run: uds run test-package --set FLAVOR=${{ inputs.flavor }} ${{ inputs.options }} --no-progress
      shell: bash

    # === UPGRADE TESTING ===

    - name: Checkout repository
      if: ${{ inputs.type == 'upgrade' }}
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      

    - name: Test upgrading the package
      if: ${{ inputs.type == 'upgrade' }}
      run: uds run test-upgrade --set FLAVOR=${{ inputs.flavor }} ${{ inputs.options }} --no-progress
      shell: bash
