name: Verify-Badge
description: Perform verification to assist with UDS badge certification

inputs:
  chartPath:
    description: Relative path to the directory with the uds-config chart
    default: chart/
  groupName:
    description: The name of the niche/group that the package fits into. E.g. package,swf,lfai
    default: package
  commonZarf:
    description: Whether or not there is a common zarf.yaml file
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Go environment
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 1.22
        check-latest: true

    - name: Helm tool installer
      uses: Azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

    - name: Test installing the package
      shell: bash
      continue-on-error: true
      run: |
        uds run badge:verify-badge \
          --set CHART_PATH="${{ inputs.chartPath }}" \
          --set GROUP_NAME="${{ inputs.groupName }}" \
          --set COMMON_ZARF="${{ inputs.commonZarf }}"
