apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-metrics
  labels:
    nginx-metrics: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
      appProtocol: http
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
