# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test-Flavor
description: Check the flavor for the UDS package

outputs:
  upgrade-flavors:
    value: ${{ steps.set-required.outputs.upgrade-flavors }}
    description: Indicates if the upgrade should be skipped

inputs:
  check-flavor-zarf-yaml:
    default: zarf.yaml
    description: Relative path of a zarf.yaml containing flavors to check

runs:
  using: composite
  steps:

    # === FLAVOR TESTING ===

    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Test latest tag deployment for flavor
      id: set-required
      run: |
        # Check if any tag exists
        TAG="$(git describe --tags "$(git rev-list --tags --max-count=1)" 2>/dev/null || echo '')"

        if [ -z "$TAG" ]; then
          echo "No Git tags found. Skipping step."
          exit 0
        fi

        # Checkout the repository at the latest tag
        git checkout "$TAG"

        # Extract upgrade flavors and set output
        echo "upgrade-flavors=$(cat ${{ inputs.check-flavor-zarf-yaml }} | yq '.components[] | select(.only | has("flavor")) | .only.flavor' | paste -s -d, - || echo '')" >> "$GITHUB_OUTPUT"
      shell: bash
