name: Test-Flavor
description: Check the flavor for the UDS package

inputs:
  flavor:
    description: Flavor of the package to test
    required: true
  type:
    description: Whether to run upgrade tests
    default: install
  options:
    description: Additional CLI options for test workflows
    default: ""

outputs:
  required:
    value: ${{ steps.set-required.outputs.required }}
    description: Indicates if the upgrade should be skipped

runs:
  using: composite
  steps:

    # === FLAVOR TESTING ===

    - name: Checkout repository
      if: ${{ inputs.type == 'upgrade' }}
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: Test latest tag deployment for flavor
      id: set-required
      if: ${{ inputs.type == 'upgrade' }}
      run: |
        uds run test-latest-tag-flavor --set FLAVOR=${{ inputs.flavor }} ${{ inputs.options }} --no-progress
        REQUIRED=$(cat require.txt)
        echo "required=$REQUIRED" >> "$GITHUB_OUTPUT"
        echo The output is $GITHUB_OUTPUT
      shell: bash
