name: Test
description: Test the UDS package

inputs:
  flavor:
    description: Flavor of the package to test
    required: true
  type:
    description: Whether to run upgrade tests
    default: install
  options:
    description: Additional CLI options for test workflows
    default: ""

outputs:
  skip:
    value: "${SKIP}"
    description: 'Indicates if the upgrade should be skipped'

runs:
  using: composite
  steps:

    # === FLAVOR TESTING ===

    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0

    - name: Test latest tag deployment for flavor
      run: uds run test-latest-tag-flavor --set FLAVOR=${{ inputs.flavor }} ${{ inputs.options }} --no-progress
      shell: bash
