# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test-Flavor
description: Check the flavor for the UDS package

outputs:
  upgrade-flavors:
    value: ${{ steps.set-required.outputs.upgrade-flavors }}
    description: Indicates if the upgrade should be skipped

inputs:
  check-flavor-zarf-yaml:
    default: zarf.yaml
    description: Relative path of a zarf.yaml containing flavors to check
  package-path:
    default: .
    description: Relative path of the package source
  docker-compose-version:
    # renovate: datasource=github-tags depName=docker/compose versioning=semver
    default: 5.5.1
    description: The Docker Compose version to install
  compose-bridge-version:
    # renovate: datasource=github-tags depName=defenseunicorns/compose-bridge-uds versioning=semver
    default: 1.2.0
    description: The Compose Bridge version to use

runs:
  using: composite
  steps:

    # === FLAVOR TESTING ===

    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: Install Docker Compose
      uses: docker/setup-compose-action@54042514f505b273907334ae2b9cdbb9a0213c1a # v2.4.0
      with:
        version: v${{ inputs.docker-compose-version }}

    - name: Test latest tag deployment for flavor
      id: set-required
      run: |
        # Check if any tag exists
        TAG="$(git describe --tags "$(git rev-list --tags --max-count=1)" 2>/dev/null || echo '')"

        if [ -z "$TAG" ]; then
          echo "No Git tags found. Skipping step."
          exit 0
        fi

        # Checkout the repository at the latest tag
        git checkout "$TAG"

        PACKAGE_DEFINITION="${{ inputs.check-flavor-zarf-yaml }}"
        if [ -f "${{ inputs.package-path }}/compose.yaml" ]; then
          docker compose \
            -f "${{ inputs.package-path }}/compose.yaml" \
            bridge convert \
            --transformation "ghcr.io/defenseunicorns/compose-bridge-uds:${{ inputs.compose-bridge-version }}" \
            --output "${{ inputs.package-path }}/build" \
            --yes
          PACKAGE_DEFINITION="${{ inputs.package-path }}/build/zarf.yaml"
        fi

        if [ ! -f "${PACKAGE_DEFINITION}" ]; then
          echo "No Zarf package definition found at ${PACKAGE_DEFINITION}."
          exit 1
        fi

        # Extract upgrade flavors and set output
        echo "upgrade-flavors=$(yq '.components[] | select(.only | has("flavor")) | .only.flavor' "${PACKAGE_DEFINITION}" | paste -s -d, - || echo '')" >> "$GITHUB_OUTPUT"
      shell: bash
