# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Callable-Pull-Request

on:
  workflow_call:
    inputs:
      runsOn:
        type: string
        default: ubuntu-latest
      flavors:
        type: string
        default: "['upstream', 'unicorn', 'registry1']"
      types:
        type: string
        default: "['install', 'upgrade']"
      reports-path:
        type: string
        description: The path to test outputs to upload
      reports-name:
        type: string
        description: The name prefix for upload test reports
        default: playwright-report
      udsCliVersion:
        description: The uds-cli version to install
        # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
        default: 0.17.0
        type: string

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
    contents: read # Allows reading the content of the repository.
    packages: read # Allows reading the content of the repository's packages.
    id-token: write

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.changes.docs }}
      main: ${{ steps.filter.outputs.changes.main }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
                - '**.md'
                - '**.jpg'
                - '**.png'
                - '**.gif'
                - '**.svg'
                - 'adr/**'
                - 'docs/**'
                - '.gitignore'
                - 'renovate.json'
                - '.release-please-config.json'
                - 'release-please-config.json'
                - 'CODEOWNERS'
                - 'LICENSE'
                - 'CONTRIBUTING.md'
                - 'SECURITY.md'
                - 'config/renovate.json5'
            main:
                - '!**.md'
                - '!**.jpg'
                - '!**.png'
                - '!**.gif'
                - '!**.svg'
                - '!adr/**'
                - '!docs/**'
                - '!.gitignore'
                - '!renovate.json'
                - '!.release-please-config.json'
                - '!release-please-config.json'
                - '!CODEOWNERS'
                - '!LICENSE'
                - '!CONTRIBUTING.md'
                - '!SECURITY.md'
                - '!config/renovate.json5'

  check-flavor:
    needs: paths-filter
    if: needs.paths-filter.outputs.main == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: test-flavor
        uses: ./.github/actions/test-flavor
        id: test-flavor
    outputs:
      upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}

  test:
    needs: check-flavor
    strategy:
      fail-fast: true
      matrix:
        types: [install, upgrade]
        flavors: ${{ fromJson(inputs.flavors) }}
    uses: ./.github/workflows/callable-test.yaml
    with:
      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
    secrets: inherit # Inherits all secrets from the parent workflow.


  run:
    needs: paths-filter
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: needs.paths-filter.outputs.main == 'true'
    strategy:
      fail-fast: true
      matrix:
        type: ${{ fromJson(inputs.types) }}
        flavor: ${{ fromJson(inputs.flavors) }}
    steps:
      - name: Shim for ${{ matrix.type }} ${{ matrix.flavor }}
        run: |
          echo "Documentation-only change detected; marking ${{ inputs.type }} ${{ inputs.flavor }} as successful."


  lint:
    uses: ./.github/workflows/callable-lint.yaml
    secrets: inherit


  commitlint:
    uses: ./.github/workflows/callable-commitlint.yaml
    secrets: inherit