# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Grype Scan

on:
  # This allows other repositories to call this workflow in a reusable way
  workflow_call:
    inputs:
      zarf_yaml:
        type: string
        default: zarf.yaml
        description: location of zarf.yaml file to scan

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allows reading the repo contents

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@b987a32bac3baeb67bfb08f5e1544e2f9076ee8a # v1.0.0
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.19.2

      - name: Environment setup
        run: |
          uds run actions:setup-environment \
            --set GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        shell: bash

      - uses: anchore/scan-action/download-grype@v3
        id: grype

      - name: run grype scan
        id: scan
        run: |
          OUTPUT_DIR=$(mktemp -d)
          uds run grype:scan --no-progress --set GRYPE_CMD="${{steps.grype.outputs.cmd}}" --set OUTPUT_DIR="${OUTPUT_DIR}" --set ZARF_YAML="${{inputs.zarf_yaml}}"
          echo "output_dir=${OUTPUT_DIR}" > "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: grype-scans
          path: ${{ steps.scan.outputs.output_dir }}
          retention-days: 30
