# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: CI Docs Shim

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string
      type:
        required: true
        type: string

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Shim for ${{ inputs.type }} ${{ inputs.flavor }}
        run: |
          echo "Documentation-only change detected; marking ${{ inputs.type }} ${{ inputs.flavor }} as successful."
