name: Cumulative Job Check

on:
  pull_request:
    types: [milestoned, opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: env