name: Cumulative Job Check

on:
  pull_request:
    types: [milestoned, opened, reopened, synchronize]

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, World!"