# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Pull Request Workflow

on:
  pull_request:
    branches: [main]
    types: [ milestoned, opened, edited, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  pull-requests: read # Allows reading pull requests

jobs:
  validate:
    permissions:
        contents: read # Allows reading the content of the repository.
        packages: read # Allows reading the content of the repository's packages.
        id-token: write
    uses: ./.github/workflows/callable-pull-request.yaml
