# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - adr/**
      - docs/**
      - .gitignore
      - renovate.json
      - .release-please-manifest.json
      - release-please-config.json
      - CODEOWNERS
      - LICENSE
      - CONTRIBUTING.md
      - SECURITY.md
      - config/renovate.json5

jobs:
  scan:
    uses: ./.github/workflows/callable-scan.yaml
    secrets: inherit # Inherits all secrets from the parent workflow.
